spring.application.name=disertatie

spring.data.mongodb.uri=mongodb://localhost:27017/disertatieDB

rsa.private-key= classpath:certificates/privateKey.pem
rsa.public-key= classpath:certificates/publicKey.pem